name       : haskell-file-embed
version    : 0.0.10
release    : 1
source     :
    - http://hackage.haskell.org/package/file-embed-0.0.10/file-embed-0.0.10.tar.gz : f751925cec5773a4fad5a48ca0a86a21091ee5f1efccf618a64a89fa2cf5f711
license    : BSD-3-Clause
component  : programming.haskell
summary    : Use Template Haskell to read a file or all the files in a directory, and turn them into (path, bytestring) pairs embedded in your haskell code.
description: |
    Use Template Haskell to read a file or all the files in a directory, and turn them into (path, bytestring) pairs embedded in your haskell code.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
