name       : haskell-file-embed
version    : 0.0.11.2
release    : 3
source     :
    - https://hackage.haskell.org/package/file-embed-0.0.11.2/file-embed-0.0.11.2.tar.gz : a4ca38940a702a5685a2433deb260d3d713dc69ef9c3ac69c9958df08dd3fe2d
license    : BSD-3-Clause
component  : programming.haskell
summary    : Use Template Haskell to read a file or all the files in a directory, and turn them into (path, bytestring) pairs embedded in your haskell code.
description: |
    Use Template Haskell to read a file or all the files in a directory, and turn them into (path, bytestring) pairs embedded in your haskell code.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
