name       : haskell-file-embed
version    : 0.0.10.1
release    : 2
source     :
    - https://hackage.haskell.org/package/file-embed-0.0.10.1/file-embed-0.0.10.1.tar.gz : 33cdeb44e8fa1ca8ade64e2b8d0924ea8c70b2b521455a0f22cde36f19314152
license    : BSD-3-Clause
component  : programming.haskell
summary    : Use Template Haskell to read a file or all the files in a directory, and turn them into (path, bytestring) pairs embedded in your haskell code.
description: |
    Use Template Haskell to read a file or all the files in a directory, and turn them into (path, bytestring) pairs embedded in your haskell code.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
